services:
  app:
    image: wesley00s/ecommerce-spring-api:latest
    build:
      context: .
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env