spring:
  devtools:
    livereload:
      enabled: true
      port: 8000
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /ecommerce
    session:
      timeout: 30m

