jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

spring:
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: ecommerce
    password:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

server:
  port: 8080
  address: 192.168.10.102
  servlet:
    context-path: /ecommerce
    session:
      timeout: 30m
#  tomcat:
#    proxy:
#      protocol-header: "X-Forwarded-Proto"
#      remote-ip-header: "X-Forwarded-For"
#      internal-proxies: ".*"
