jwt:
  key:
    private:
      path: classpath:certs/private_key.pem
    public:
      path: classpath:certs/public_key.pem

app:
  issuer: ${ISSUER}

spring:
  devtools:
    livereload:
      enabled: true
      port: 8000
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /ecommerce/api
    session:
      timeout: 30m

springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.data.jpa: INFO

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
