jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

spring:
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: ecommerce
    password:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

server:
  port: 8080
  address: localhost
  servlet:
    context-path: /ecommerce
    session:
      timeout: 30m