CREATE TABLE address
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street VARCHAR(255),
    city   VARCHAR(255),
    state  VARCHAR(255),
    zip    VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE cart
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    is_active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_products
(
    cart_id     BIGINT NOT NULL,
    products_id BIGINT NOT NULL
);

CREATE TABLE order_shopping
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT,
    quantity   INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    status     SMALLINT,
    CONSTRAINT pk_order_shopping PRIMARY KEY (id)
);

CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(255),
    name           VARCHAR(255),
    description    VARCHAR(10000),
    price          DECIMAL,
    stock_quantity INTEGER,
    image_url      VARCHAR(255),
    category       SMALLINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE users
(
    user_id    UUID         NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255),
    user_type  SMALLINT,
    address_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_address UNIQUE (address_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE order_shopping
    ADD CONSTRAINT FK_ORDER_SHOPPING_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE cart_products
    ADD CONSTRAINT fk_carpro_on_cart FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_products
    ADD CONSTRAINT fk_carpro_on_product FOREIGN KEY (products_id) REFERENCES product (id);