CREATE TABLE address
(
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street     VARCHAR(255),
    city       VARCHAR(255),
    state      VARCHAR(255),
    zip        VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (address_id)
);

CREATE TABLE users
(
    user_id    UUID         NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255),
    user_type  SMALLINT,
    address_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uc_users_address UNIQUE (address_id),
    CONSTRAINT uc_users_email UNIQUE (email),
    CONSTRAINT FK_USERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (address_id)
);

CREATE TABLE cart
(
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID,
    CONSTRAINT pk_cart PRIMARY KEY (cart_id),
    CONSTRAINT FK_CART_ON_USER_USERID FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE product
(
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    VARCHAR(10000),
    price          DECIMAL,
    stock_quantity INTEGER,
    image_url      VARCHAR(255),
    category       SMALLINT,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE shopping
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT,
    product_id BIGINT,
    quantity   INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_shopping PRIMARY KEY (id),
    CONSTRAINT FK_SHOPPING_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (cart_id),
    CONSTRAINT FK_SHOPPING_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id)
);