CREATE TABLE product_category
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    image_url       VARCHAR(255),
    image_public_id VARCHAR(255),
    CONSTRAINT pk_productcategory PRIMARY KEY (id)
);