name: Deployment

on:
  workflow_run:
    workflows: ['Application Unit Tests']
    branches: [main]


jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Permissions
        run: sudo chmod 666 /var/run/docker.sock

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Compose Run Build
        run: |
          docker compose up --build -d
          docker tag ecommerce-api-image:latest wesley00s/ecommerce-spring-api:v3
          docker push wesley00s/ecommerce-spring-api:v3