name: Application Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure .env
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" > src/main/resources/.env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> src/main/resources/.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> src/main/resources/.env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> src/main/resources/.env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> src/main/resources/.env
          echo "ISSUER=${{ secrets.ISSUER }}" >> src/main/resources/.env

      - name: Create RSA Keys
        run: |
          echo "${{ secrets.APP_PRIVATE_KEY }}" > src/main/resources/app.key
          chmod 600 src/main/resources/app.key
          echo "${{ secrets.APP_PUBLIC_KEY }}" > src/main/resources/app.pub

      - name: Run Tests
        run: ./gradlew :test